# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "api_time",
    srcs = ["api_time.cc"],
    deps = ["//cyber"],
)
cc_binary(
    name = "api_duration",
    srcs = ["api_duration.cc"],
    deps = ["//cyber"],
)
cc_binary(
    name = "api_rate",
    srcs = ["api_rate.cc"],
    deps = ["//cyber"],
)
cc_binary(
    name = "api_timer",
    srcs = ["api_timer.cc"],
    deps = ["//cyber"],
)
cc_binary(
    name = "api_log",
    srcs = ["api_log.cc"],
    deps = ["//cyber"],
)