// Generated by gencpp from file package/hello.msg
// DO NOT EDIT!


#ifndef PACKAGE_MESSAGE_HELLO_H
#define PACKAGE_MESSAGE_HELLO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace package
{
template <class ContainerAllocator>
struct hello_
{
  typedef hello_<ContainerAllocator> Type;

  hello_()
    : name()  {
    }
  hello_(const ContainerAllocator& _alloc)
    : name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;





  typedef boost::shared_ptr< ::package::hello_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::package::hello_<ContainerAllocator> const> ConstPtr;

}; // struct hello_

typedef ::package::hello_<std::allocator<void> > hello;

typedef boost::shared_ptr< ::package::hello > helloPtr;
typedef boost::shared_ptr< ::package::hello const> helloConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::package::hello_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::package::hello_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::package::hello_<ContainerAllocator1> & lhs, const ::package::hello_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::package::hello_<ContainerAllocator1> & lhs, const ::package::hello_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::package::hello_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::package::hello_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::package::hello_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::package::hello_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::package::hello_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::package::hello_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::package::hello_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c1f3d28f1b044c871e6eff2e9fc3c667";
  }

  static const char* value(const ::package::hello_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc1f3d28f1b044c87ULL;
  static const uint64_t static_value2 = 0x1e6eff2e9fc3c667ULL;
};

template<class ContainerAllocator>
struct DataType< ::package::hello_<ContainerAllocator> >
{
  static const char* value()
  {
    return "package/hello";
  }

  static const char* value(const ::package::hello_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::package::hello_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
;
  }

  static const char* value(const ::package::hello_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::package::hello_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct hello_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::package::hello_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::package::hello_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PACKAGE_MESSAGE_HELLO_H
