# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "para_server",
    srcs = ["para_server.cc"],
    deps = [
        "//cyber",
        "//cyber/parameter"
    ],
)

cc_binary(
    name = "para_client",
    srcs = ["para_client.cc"],
    deps = [
        "//cyber",
        "//cyber/parameter"
    ],
)