CREATE TABLE
    student (
        SNO CHAR(7) PRIMARY KEY,
        SNAME CHAR(10) NOT NULL,
        SSEX ENUM('男', '女'),
        SAGE SMALLINT,
        SDEPT VARCHAR(20) DEFAULT '计算机系'
    );

CREATE Table
    dept (
        dno CHAR(3) PRIMARY KEY,
        dname VARCHAR(20) NOT NULL,
        mgr CHAR(5),
        FOREIGN KEY(mgr) REFERENCES emp(eno) ON DELETE RESTRICT ON UPDATE CASCADE
    );

CREATE TABLE
    sg (
        SNO CHAR(5) NOT NULL,
        GNO CHAR(6) NOT NULL,
        QUANTITY INT,
        PRIMARY KEY (SNO, GNO),
        FOREIGN KEY (SNO) REFERENCES store(SNO) ON DELETE RESTRICT ON UPDATE CASCADE,
        FOREIGN KEY (GNO) REFERENCES goods(GNO) ON DELETE RESTRICT ON UPDATE CASCADE
    );

ALTER TABLE sg MODIFY COLUMN indate DATE;

ALTER TABLE emp
ADD dno CHAR(3),
ADD
    FOREIGN KEY (dno) REFERENCES dept(dno) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE dept
ADD
    FOREIGN KEY (mgr) REFERENCES emp(eno) ON DELETE RESTRICT ON UPDATE CASCADE;

CREATE TABLE
    price_log (
        id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        product_id INT UNSIGNED NOT NULL,
        price DECIMAL(10, 2),
        create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        FOREIGN KEY (product_id) REFERENCES product(product_id) ON DELETE CASCADE ON UPDATE CASCADE
    );

ALTER TABLE spj ADD COLUMN id INT AUTO_INCREMENT PRIMARY KEY;

ALTER Table spj ADD FOREIGN KEY(SNO) REFERENCES s(SNO);

ALTER Table spj
ADD
    FOREIGN KEY(PNO) REFERENCES p(PNO) ON DELETE CASCADE;

ALTER Table spj
ADD
    FOREIGN KEY(JNO) REFERENCES j(JNO) ON UPDATE CASCADE;

ALTER Table course MODIFY COLUMN CNAME VARCHAR(30);

ALTER TABLE p ADD COLUMN GUIGE VARCHAR(50);

CREATE TABLE
    j (
        JNO CHAR(6) PRIMARY KEY,
        JNAME VARCHAR(20) NOT NULL,
        CITY VARCHAR(50)
    );

CREATE TABLE
    s (
        SNO CHAR(6) PRIMARY KEY,
        SNAME VARCHAR(20) NOT NULL,
        SSTATUS SMALLINT(2) CHECK(
            sstatus = '0'
            OR sstatus = '1'
        ),
        CITY VARCHAR(50)
    );

CREATE TABLE
    spj (
        SNO CHAR(6),
        PNO CHAR(6),
        JNO CHAR(6),
        QTY SMALLINT DEFAULT 100,
        PRIMARY KEY (SNO, PNO, JNO)
    );

CREATE TABLE
    p (
        PNO CHAR(6) PRIMARY KEY,
        PNAME VARCHAR(20) NOT NULL,
        COLOR ENUM('红', '绿', '蓝'),
        WEIGHT DECIMAL(9, 2) DEFAULT 1.0
    );

CREATE TABLE
    sc (
        SNO CHAR(7),
        CNO CHAR(10),
        GRADE SMALLINT,
        PRIMARY KEY (SNO, CNO),
        FOREIGN KEY (SNO) REFERENCES Student(SNO) ON DELETE RESTRICT ON UPDATE CASCADE,
        FOREIGN KEY (CNO) REFERENCES Course(CNO) ON DELETE RESTRICT ON UPDATE CASCADE
    );

CREATE TABLE
    course (
        CNO CHAR(10) PRIMARY KEY,
        CNAME VARCHAR(20) NOT NULL UNIQUE,
        CCREDIT SMALLINT CHECK(CCREDIT > 0),
        SEMSTER SMALLINT CHECK(SEMSTER > 0),
        PERIOD SMALLINT CHECK(PERIOD > 0)
    );

CREATE TABLE
    emp (
        eno CHAR(5) PRIMARY KEY,
        ename CHAR(8) NOT NULL,
        esex CHAR(1) CHECK(
            esex = 'm'
            OR esex = 'f'
        ),
        birth DATE,
        salary NUMERIC(9, 2) DEFAULT 0.00
    );